site_name: '${{values.name}}'
site_description: 'Main documentation for ${{values.name}}'
repo_url: https://github.com/adi-nagesh/${{values.name}}
edit_uri: edit/main/docs

plugins:
  - techdocs-core
  - redirects:
      redirect_maps:
        'index.md': 'docs/index.md'

# For sidebar navigation on https://backstage.io/, see `microsite/sidebars.js`
nav:
  - Overview:
      - Getting started: 'docs/index.md'